/**
 * Fixed German wording for the app (Phase 2, no language model).
 */
import type { CaptureMethod } from '../../engine/capture';
import type { HarmonyKind } from '../../engine/harmony';
import type { Side, VictoryClass } from '../../engine/types';

export const sideName: Record<Side, string> = { white: 'Weiß', black: 'Schwarz' };
export const methodName: Record<CaptureMethod, string> = {
  meeting: 'Begegnung',
  ambush: 'Hinterhalt',
  assault: 'Angriff',
  siege: 'Belagerung',
};
export const kindName: Record<HarmonyKind, string> = {
  arithmetic: 'arithmetisch',
  geometric: 'geometrisch',
  musical: 'musikalisch',
};
export const victoryName: Record<VictoryClass, string> = {
  minor: 'Kleiner Sieg',
  major: 'Großer Sieg',
  greatest: 'Größter Sieg',
};

export const texts = {
  appTitle: 'Rithmos',
  sideNameShort: (side: Side) => (side === 'white' ? 'W' : 'S'),
  play: 'Spielen',
  coverage: 'Deckung',
  rules: 'Regeln',
  newGame: 'Neues Spiel',
  yourMove: 'Du bist am Zug. Tippe einen eigenen Stein.',
  chooseTarget: 'Tippe das Zielfeld, oder einen anderen Stein.',
  capturePrompt: 'Schläge: eigene Steine als Angreifer antippen, dann den gegnerischen Stein. Oder den Zug beenden.',
  chooseAttacker: 'Wähle zuerst den angreifenden Stein.',
  endTurn: 'Zug beenden',
  captured: (method: CaptureMethod, value: number) => `${methodName[method]}: ${value} geschlagen.`,
  capturedComponent: (method: CaptureMethod, value: number) => `${methodName[method]}: Pyramidenteil ${value} geschlagen.`,
  opponentThinking: 'Gegner denkt …',
  opponentMoved: (value: number, from: string, to: string) => `Gegner zieht ${value} von ${from} nach ${to}.`,
  opponentCaptured: (method: CaptureMethod, value: number) => `${methodName[method]}: dein Stein ${value} wurde geschlagen.`,
  opponentCannotMove: 'Der Gegner kann nicht ziehen und setzt aus.',
  youCannotMove: 'Du kannst nicht ziehen und setzt aus.',
  won: (side: Side, victory: VictoryClass, kinds: readonly HarmonyKind[], values: readonly number[]) =>
    `${victoryName[victory]} für ${sideName[side]}: ${values.join(' · ')}, ${kinds.map((k) => kindName[k]).join(' und ')}.`,
  markPrompt: 'Markiere die Felder, die deiner Meinung nach eine erreichbare Harmonie bilden. Dann weiter.',
  markHintOne: 'Eine erreichbare Harmonie existiert.',
  markHintNone: 'Keine erreichbare Harmonie in dieser Stellung.',
  markHintCount: (n: number) => (n === 1 ? 'Eine erreichbare Harmonie.' : `${n} erreichbare Harmonien.`),
  markContinue: 'Weiter zum Zug',
  markSkip: 'Ohne Markierung weiter',
  coverageResult: (pct: number) => `Deckung dieses Zuges: ${pct} %.`,
  coverageNone: 'Keine Harmonie erreichbar, dieser Zug zählt nicht für die Deckung.',
  assistName: ['Stufe 0: nichts', 'Stufe 1: Hinweis', 'Stufe 2: Anzahl', 'Stufe 3: alle Harmonien'] as const,
  strengthName: { novice: 'Novize', apprentice: 'Geselle', master: 'Meister' } as const,
  side: 'Deine Farbe',
  strength: 'Gegnerstärke',
  assist: 'Harmonie-Anzeige',
  start: 'Spiel starten',
  ruleSet: 'Regelfassung',
  loading: 'Lädt …',
  apiError: (detail: string) => `Der Server antwortet nicht (${detail}). Das Spiel läuft weiter, die Ablage wird später nachgeholt.`,
  middles: 'Middles',
  middlesIntro: (side: Side) =>
    `${sideName[side]} am Zug. Zwei Steine einer Harmonie stehen schon. Finde das Feld, auf dem der mittlere Stein sie mit einem Zug vollendet.`,
  middlesTap: 'Tippe den Stein, dann das Zielfeld.',
  middlesWrong: (n: number) => `Keine Harmonie. Versuch ${n}.`,
  middlesSolved: (kinds: readonly string[], values: readonly number[], tries: number) =>
    `Gelöst mit Versuch ${tries}: ${values.join(' · ')}, ${kinds.join(' und ')}.`,
  middlesGiveUp: 'Auflösen',
  middlesGaveUp: 'Aufgelöst. Morgen gibt es ein neues Rätsel.',
  middlesAlready: 'Das heutige Rätsel hast du schon gespielt. Morgen gibt es ein neues.',
  middlesSolution: (from: string, to: string, values: readonly number[], kinds: readonly string[]) =>
    `Lösung: ${from} nach ${to}, ${values.join(' · ')}, ${kinds.join(' und ')}.`,
  distributionTitle: (attempts: number, solved: number) => `Verteilung: ${solved} von ${attempts} gelöst, nach Versuchen`,
  distributionUnavailable: 'Verteilung gerade nicht verfügbar.',
  distributionOffline: 'Ohne Server keine Verteilung. Das Rätsel wurde lokal erzeugt.',
  offlineNote: 'Offline-Rätsel, lokal erzeugt und mit dem Solver geprüft.',
  difficulty: ['leicht', 'mittel', 'schwer'] as const,

  // Middles without the board (Stufe 1). One sentence per screen.
  triadNumber: (n: number) => `Nº ${n}`,
  triadStreak: (days: number) => (days === 1 ? '1 Tag in Folge' : `${days} Tage in Folge`),
  triadQuestion: (kind: HarmonyKind) => `Welche Zahl macht die Reihe ${kindName[kind]}?`,
  triadTry: (n: number, max: number) => `Versuch ${n} von ${max}`,
  triadOtherMean: (answer: number, mean: HarmonyKind) => `${answer} ist das ${meanName[mean]} — hier ist eine andere Harmonie gefragt.`,
  triadWrong: (answer: number) => `${answer} macht keine Harmonie aus den dreien.`,
  triadOff: (value: number) => `Daneben — du warst bei ${value.toFixed(1).replace('.', ',')}.`,
  triadRevealed: (b: number) => `Die Mitte war ${b}. Morgen gibt es eine neue.`,
  triadPlayedToday: 'Heute schon gespielt. Morgen gibt es eine neue Mitte.',
  triadListen: 'Dreiklang anhören',
  findSource: 'Quelle',
  voiceMonk: 'Der Mönch',
  voiceAnalyst: 'Die Analystin',
  aiLabel: 'Vom Sprachmodell formuliert, von der Engine geprüft.',
  whoLiesQuestion: 'Drei Erklärungen, eine stimmt. Welche?',
  whoLiesRight: 'Richtig, die stimmt.',
  whoLiesWrong: (i: number) => `Nein, das war eine Lüge. Die ${i + 1}. stimmt.`,
  findLine: (title: string, where: string) => `${title} · ${where}`,
  triadShare: 'Teilen',
  triadCopied: 'Kopiert.',
  triadScore: (n: number, tries: number | null, max: number) => `Nº ${n} · ${tries === null ? 'X' : tries}/${max}`,
  triadDistribution: (attempts: number, solved: number) => (attempts === 0 ? 'Du bist heute die erste Person.' : `${solved} von ${attempts} haben es heute gelöst.`),
  triadOffline: 'Ohne Server: das Rätsel kommt aus dem Gerät.',
  intervalName: {
    unison: 'Grundton',
    minorThird: 'kleine Terz',
    majorThird: 'große Terz',
    fourth: 'Quarte',
    fifth: 'Quinte',
    octave: 'Oktave',
    twelfth: 'Oktave und Quinte',
    doubleOctave: 'zwei Oktaven',
  } as const,
  // Practice and the hit rate (Stufe 2)
  tabToday: 'Heute',
  tabPractice: 'Üben',
  tabChain: 'Kette',
  tabSkill: 'Deckung',
  chain: 'Die Kette',
  chainQuestion: 'Wie lang wird die Kette?',
  chainLinks: (n: number, best: number) => (n === 1 ? `Ein Glied · bis zu ${best} möglich` : `${n} Glieder · bis zu ${best} möglich`),
  chainStuck: (n: number, best: number) => `Hier geht es nicht weiter: ${n} von ${best}.`,
  chainDone: (best: number) => `Die längste Kette des Tages: ${best} Glieder.`,
  chainLink: (kind: HarmonyKind) => `${kindName[kind]}`,
  chainReset: 'Neu legen',
  chainReveal: 'Auflösen',
  chainRevealed: (chain: readonly number[]) => `Die längste Kette: ${chain.join(' · ')}.`,
  practice: 'Üben',
  practiceLevel: (level: number) => `Stufe ${level} von 5`,
  practiceLevelName: ['arithmetisch', 'geometrisch', 'musikalisch', 'welches Mittel?', 'vier Zahlen'] as const,
  practiceUnlock: (remaining: number, next: number) => (remaining === 1 ? `Noch eine gelöste bis Stufe ${next}.` : `Noch ${remaining} gelöste bis Stufe ${next}.`),
  practiceAllOpen: 'Alle fünf Stufen sind offen.',
  whichQuestion: 'Welches Mittel ist das?',
  whichWrong: (kind: HarmonyKind) => `Nicht ${kindName[kind]}. Noch ein Versuch.`,
  whichRevealed: (kind: HarmonyKind) => `Es war ${kindName[kind]}.`,
  whichSolved: (b: number, a: number, c: number, kind: HarmonyKind) => `${b} ist das ${meanName[kind]} von ${a} und ${c}.`,
  fourQuestion: 'Zwei Mitten fehlen: die harmonische und die arithmetische.',
  fourOne: (placed: number, mean: HarmonyKind) => `${placed} ist das ${meanName[mean]} — eine fehlt noch.`,
  fourWrong: (answer: number) => `${answer} ist keins der beiden Mittel.`,
  fourSolved: (a: number, hm: number, am: number, d: number) => `${a} · ${hm} · ${am} · ${d}: die Tetraktys, harmonisch und arithmetisch zugleich.`,
  fourRevealed: (hm: number, am: number) => `Die Mitten waren ${hm} und ${am}.`,
  next: 'Weiter',
  skillTitle: 'Deckung',
  skillIntro: 'Wie viel von dem, was die Engine sieht, siehst du ohne Hilfe? Trefferquote je Mittel, letzte 50 Rätsel.',
  skillNone: 'noch keins',
  skillRate: (solved: number, n: number) => `${Math.round((solved / n) * 100)} % · ${solved} von ${n}`,
  skillWeeks: 'Nach Wochen',
  skillWeekRow: (week: string) => `ab ${week}`,
  skillNoWeeks: 'Nach der ersten Woche erscheint hier der Verlauf.',
  skillLagging: (kind: HarmonyKind) => `Zieht hinterher: ${kindName[kind]}. Die Übung nimmt es öfter dran.`,
  skillLevel: (level: number) => `Übung: Stufe ${level} von 5 offen.`,
  hunt: 'Harmonie-Jagd',
  huntIntro: 'Fotografiere etwas, das sich zählen lässt: ein Regal, eine Fassade, einen Tisch.',
  huntPick: 'Foto wählen',
  huntGuess: 'Steckt darin eine Harmonie?',
  huntYes: 'Ja',
  huntNo: 'Nein',
  huntCounting: 'Das Modell zählt …',
  huntCounts: (n: number) => (n === 1 ? 'Eine Gruppe gezählt.' : `${n} Gruppen gezählt.`),
  huntFound: (kind: HarmonyKind, a: string, b: string, c: string) => `${a}, ${b}, ${c}: ${kindName[kind]}.`,
  huntNone: 'Keine Harmonie unter den gezählten Dingen.',
  huntRight: 'Du hast es vor dem Modell gesehen.',
  huntWrong: 'Das Modell hat gezählt, die Engine hat entschieden: anders als getippt.',
  huntUnavailable: 'Die Jagd braucht den Server und ein Bildmodell. Heute nicht verfügbar.',
  huntTooMany: 'Genug gejagt für heute.',
  huntRemaining: (n: number) => (n === 1 ? 'Noch eine Jagd heute.' : `Noch ${n} Jagden heute.`),
  huntAgain: 'Noch eine',
  // The small board (Stufe 4)
  tabBoard: 'Brett',
  board: 'Das kleine Brett',
  boardLocked: 'Das Brett öffnet sich, wenn alle fünf Übungsstufen offen sind.',
  boardTurn: (n: number) => `Zug ${n}`,
  boardYourMove: 'Du bist am Zug.',
  boardWhy: 'Warum dieser Zug?',
  boardNoReason: 'Einfach so',
  boardReason: {
    close: (values: readonly number[]) => `Ich schließe ${values.join(' · ')}.`,
    build: (values: readonly number[]) => `Ich bereite ${values.join(' · ')} vor.`,
    threat: (values: readonly number[]) => `Ich drohe der ${values[0]}.`,
    escape: (values: readonly number[]) => `Ich bringe den Stein vor der ${values[0]} weg.`,
  } as const,
  // The four fields of CLAUDE.md 6. Provisional wording, a Wolf-Ping.
  verdict: {
    understood: 'Verstanden: starker Zug, und der Grund stimmt.',
    luck: 'Glück: starker Zug, aber aus einem anderen Grund als gedacht.',
    slip: 'Rechenfehler: der Grund stimmt, der Zug ist trotzdem schwach.',
    misread: 'Missverständnis: der Grund trifft nicht zu, und der Zug ist schwach.',
    none: '',
  } as const,
  boardOpponentThinks: 'Der Gegner überlegt.',
  intent: {
    complete_harmony: (values: readonly number[]) => `Der Gegner schließt ${values.join(' · ')}.`,
    capture: (n: number) => (n === 1 ? 'Der Gegner schlägt einen Stein.' : `Der Gegner schlägt ${n} Steine.`),
    build_harmony: (values: readonly number[]) => `Der Gegner bereitet ${values.join(' · ')} vor.`,
    escape: 'Der Gegner bringt einen Stein in Sicherheit.',
    block: (values: readonly number[]) => `Der Gegner stört dein ${values.join(' · ')}.`,
    develop: 'Der Gegner rückt vor.',
  } as const,
  boardWon: (values: readonly number[]) => `Gewonnen: ${values.join(' · ')} steht.`,
  boardLost: (values: readonly number[]) => `Verloren: ${values.join(' · ')} steht gegen dich.`,
  boardAgain: 'Noch einmal',
  boardSide: { white: 'Weiß', black: 'Schwarz' } as const,
  boardMeeting: 'Begegnung: gleicher Wert in Reichweite wird geschlagen.',
  boardFull: 'Das volle Brett',
  boardFullNote: 'Nach Mebben: 8 × 16, 48 Steine, vier Schlagarten. Für die, die es wollen.',
  boardSmallNote: '4 × 8, vier Steine je Seite, die Begegnung.',
  boardChoose: 'Welches Brett?',
  boardMarkQuestion: 'Wo ist eine Harmonie erreichbar?',
  boardMarkNone: 'Keine Harmonie in Reichweite, dieser Zug zählt nicht für die Deckung.',
  boardMarkResult: (pct: number) => `Deckung dieses Zuges: ${pct} %.`,
  boardMarkContinue: 'Weiter',
  boardBack: 'Zurück',
  skillBoardTitle: 'Auf dem Brett',
  skillBoardLabel: 'Markiert, was die Engine sieht',
  skillBoardAverage: (pct: number, n: number) => `${pct} % über die letzten ${n} Züge`,
  skillBoardNone: 'Noch kein Zug mit Markierung.',
  rulesAskTitle: 'Frag die Regelfassung',
  rulesAskPlaceholder: 'Darf ein Dreieck gerade ziehen?',
  rulesAsk: 'Fragen',
  rulesAskBusy: 'Das Modell liest nach …',
  rulesAskOff: 'Heute nicht verfügbar.',
  rulesAskDone: 'Heute keine Fragen mehr.',
  rulesAskError: 'Keine Verbindung.',
  rulesAskRemaining: (n: number) => (n === 1 ? 'Eine Frage heute noch.' : `${n} Fragen heute noch.`),
  settings: 'Einstellungen',
  settingsSound: 'Klang',
  settingsTheme: 'Erscheinung',
  themeName: { dark: 'Dunkel', light: 'Hell' } as const,
  on: 'An',
  off: 'Aus',
  close: 'Schließen',
  ruleSetNote: (name: string, source: string) => `Regelfassung: ${name}. Quelle: ${source}`,
} as const;

export const meanName: Record<HarmonyKind, string> = {
  arithmetic: 'arithmetische Mittel',
  geometric: 'geometrische Mittel',
  musical: 'harmonische Mittel',
};

/**
 * The one sentence after solving: where this mean sits in the world today.
 * Fixed text until the narrator (Stufe 3) takes over; the applications come
 * from engine/rules/applications.ts, three per kind, rotated by day.
 */
export function triadSentence(kind: HarmonyKind, a: number, b: number, c: number, variant: number): string {
  const lead = `${b} ist das ${meanName[kind]} von ${a} und ${c}`;
  const uses: Record<HarmonyKind, readonly string[]> = {
    arithmetic: [
      `${lead} — der Durchschnitt, den du aus jeder Messreihe kennst: alles zusammen, geteilt durch die Anzahl.`,
      `${lead} — genau so glättet ein gleitender Mittelwert eine Kurve, Punkt für Punkt.`,
      `${lead} — dieselbe Rechnung, mit der aus Noten ein Schnitt wird.`,
    ],
    geometric: [
      `${lead} — so rechnet man eine durchschnittliche Wachstumsrate: nicht addieren, sondern multiplizieren und die Wurzel ziehen.`,
      `${lead} — Zinseszins über mehrere Jahre folgt genau dieser Proportion.`,
      `${lead} — damit werden Verhältnisse vergleichbar gemacht, wenn die Größenordnungen weit auseinanderliegen.`,
    ],
    musical: [
      `${lead} — so berechnet man die Durchschnittsgeschwindigkeit, wenn du hin ${a} und zurück ${c} fährst.`,
      `${lead} — der F1-Score, mit dem Klassifikationsmodelle bewertet werden, ist genau dieses Mittel.`,
      `${lead} — zwei Widerstände parallel geschaltet ergeben nach dieser Proportion ihren gemeinsamen Wert.`,
    ],
  };
  const list = uses[kind];
  return list[((variant % list.length) + list.length) % list.length]!;
}
